name: Deploy WAR app from GitHub Repo to Azure Web App

env:
  AZURE_WEBAPP_NAME: simo1

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le dépôt contenant le fichier WAR
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Authentification avec Azure
      - name: Azure Login with Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Étape 3 : Vérifier l'existence du fichier WAR
      - name: Check for WAR file
        run: |
          if [ ! -f "simple-webapp.war" ]; then
            echo "Error: WAR file not found!"
            exit 1
          fi

      # Étape 4 : Déployer le fichier WAR sur Azure Web App
      - name: Deploy WAR file to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: 'simple-webapp.war'

